### PR TITLE
python 3.8 support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@nehaljwani, according to https://github.com/pyinstaller/pyinstaller/issues/5185#issuecomment-696382896, 4.0 had only a couple of issues for python 3.8, so, I'm sending this PR to see how far it goes.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@conda-forge/pyinstaller, this is ready for review. Adding python3.8 support because `osx-arm64` platform doesn't support `py<38`.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by jakirkham** [comment]
Upstream has not made a release with Python 3.8 support as noted in the other PR trying to do this ( https://github.com/conda-forge/pyinstaller-feedstock/pull/34#issuecomment-581073747 )

**Comment by isuruf** [comment]
That's true, but see https://github.com/pyinstaller/pyinstaller/issues/5185#issuecomment-696382896, which means it's okay to have it until there's a new release. (Same issue with python 3.9. None of the software that we are building in the python 3.9 migration has a python 3.9 release, but most of them work enough to add a build)

**Comment by isuruf** [comment]
I can disable py38 for other platforms and keep it only for `osx-arm64` if you prefer.

**Comment by nehaljwani** [comment]
I'm fine with merging this unless someone objects in the next 24 hours.

**Comment by isuruf** [comment]
Right on time. :smile: Thanks @nehaljwani

**Pull request merged**
