### PR TITLE
Setuptools constraint

### PR DESCRIPTION
**Pull request by msarahan**
pypa/setuptools#1963

blocking conda-forge/conda-standalone-feedstock#5

### CODE REVIEW

**Comment by msarahan** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
We might need to force linking to `libc++` on macOS.

**Comment by msarahan** [comment]
Can you please link to an example? I unfortunately have lost track of current common workarounds.

**Comment by msarahan** [comment]
Oh, and Mac was disabled here. It would be good to enable it if we can.

**Pull request closed without merging**
