### PR TITLE
Update to 3.3.1

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Hmm...need help with something @nicoddemus?

**Comment by nicoddemus** [comment]
Thanks @jakirkham, for some reason the CircleCI build failed out of nowhere (killed) I'm trying to trigger it again. I will push a new branch shortly. 😉

**Comment by jakirkham** [comment]
Sure. Let me know if you are still having issues with the new branch.

**Comment by nicoddemus** [comment]
OK, thanks! 😁

**Pull request closed without merging**
