### PR TITLE
Updating to v3.3

### PR DESCRIPTION
**Pull request by rth**
Updating to the latest version of pyinstaller (3.3)...

### CODE REVIEW

**Comment by jakirkham** [comment]
Please add `license_file: COPYING.txt` to the `about` section after `license`.

**Comment by jakirkham** [comment]
Looks like it has a new dependency, `dis3`? Maybe there are others?

**Comment by rth** [comment]
@jakirkham Thanks for the review! 

Yes, looks like there are two additional dependencies on Python 2.7, neither of which are on conda-forge for the moment. From `setup.py`,
```py
# dis3 and xdis are used for our version of modulegraph
if sys.version_info < (3,):
    REQUIREMENTS.append('dis3')
elif sys.version_info < (3, 4):
    REQUIREMENTS.append('xdis')
```
I guess those would need to be added first? Alternatively maybe skip 2.7 for now and only build 3.5, 3.6 as a temporary solution?

**Comment by jakirkham** [comment]
What would go into adding those dependencies to conda-forge? Are they standalone or do they have dependencies that we don't have too? Also are they pure Python or do they have compiled portions?

**Comment by rth** [comment]
Actually looking into it further, on py 2.7 only dis3 package is necessary. It is imported only once [here](https://github.com/pyinstaller/pyinstaller/blob/656fae0af179064e97b68d19734263b6083bf734/PyInstaller/lib/modulegraph/_compat.py#L29) .

dis3 (backport of dis on Python 3) available from here https://pypi.python.org/pypi/dis3. The latest update is from 2015 and the linked github repo doesn't exist anymore, so I don't think it would make sense to add it as a standalone package on conda-forge. It also contains a single (pure python) file `dis3.py` of ~500 lines.

Maybe just add `dis3.py` with a patch somewhere under the namespace of pyinstaller then update the path in that import line? Then, possibly, open an issue on pyinstaller's repo asking them if they would consider bundling it in the future?

**Comment by jakirkham** [comment]
So if it is that simple to add and there won't be any updates, the let's actually package `dis3`. That makes it easier if other things depend on it down the road. It will be a bit of a one off, but backports packages tend to be like that anyways. Do you mind adding a PR to staged-recipes?

Side note: Looking at `xdis` a bit, it seems like that is a better backports package as it has Python 2/3 support. Might be worth asking upstream why they depend on `dis3` at all instead of just moving to `xdis` (especially as it is maintained by some of the same devs 😄).

**Comment by rth** [comment]
Sure, I don't mind creating a PR for a dis3 feedstock, if you think we should go that way, depending on the answer in the comment you raised...

**Comment by jakirkham** [comment]
Yeah, sounds like it.

**Comment by rth** [comment]
@jakirkham So dis3 dependency is added. 

Unfortunately, it looks like pyinstaller also added a new dependency https://pypi.python.org/pypi/macholib/ which itself pulls https://pypi.python.org/pypi/altgraph/  neither of which are on conda forge. Both appear to be well maintained with some number of forks etc on bitbucket. Should I make a PR to add them? Actually can I add both in a single PR (if one depends on another) ?

**Comment by jakirkham** [comment]
Yes please. Feel free to use one PR. Thanks.

**Comment by rth** [comment]
Added macholib dependency but Appveyor is failing with,
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::anaconda-client-1.6.5-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
```

will try to re-render to see if it helps..

**Comment by rth** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Nearly certain that re-rendering does fix that issue.

**Comment by jakirkham** [comment]
LGTM too. Thanks for your hard work on this @rth!

**Comment by nicoddemus** [comment]
Thanks again @rth!

**Comment by jakirkham** [comment]
Travis CI done in 8hrs! 🎉 That's exciting! 😄

**Comment by rth** [comment]
> Travis CI done in 8hrs! :tada: That's exciting! :smile:

Great work on optimizing resources to make the various builds faster!

**Pull request merged**
